### ISSUE TITLE
cookies中wechatSESS_ID问题

### ISSUE THREAD

**Issue by JRICKL** [qmppz/igotolibrary#1]
发现wechatSESS_ID在变化，上午测试和下午测试的不一样，请问wechatSESS_ID变化周期你清楚吗？

**Comment by qmppz** [comment]
不定时更新，所以尽量在开抢前1小时抓包获取id

**Comment by qmppz** [comment]
回答见楼上

**Comment by liangduidong** [comment]
怎么动态抓取这个wechatSESS_ID呢？
