### ISSUE TITLE
部署在自己租的服务器上(PC上也试了)了，任务也添加成功了，但是执行失败了，用#jg指令查询抢座结果程序报出错了，不知道怎么改了，大佬如果看见了，指点一下我吧，比我瞎琢磨一天都有用

### ISSUE THREAD

**Issue by Zi-x** [qmppz/igotolibrary#26]
![QQ图片20201015085520](https://user-images.githubusercontent.com/47513451/96060883-522d2000-0ec4-11eb-98a0-49b11ade672f.png)

**Comment by Zi-x** [comment]
数据库里的task_result也是什么都没有

**Comment by Zi-x** [comment]
刚试了在自己电脑上用捡漏功能，提示指令提交成功了，但用fiddler抓包发现是，一直在404网页里请求(捡漏)
![20201015182541](https://user-images.githubusercontent.com/47513451/96111764-3d787880-0f14-11eb-88fa-c8168cdde8da.png)
用查询捡漏结果还是报之前在服务器上的类似错误：
Traceback (most recent call last):
  File "E:\google下载\igotolibrary-master\utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "E:\google下载\igotolibrary-master\utils.py", line 1071, in get_value
    result = self.client.get(key=key, default=default)
  File "C:\Users\Orange\AppData\Local\Programs\Python\Python37\lib\site-packages\pymemcache\client\base.py", line 534, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "C:\Users\Orange\AppData\Local\Programs\Python\Python37\lib\site-packages\pymemcache\client\base.py", line 899, in _fetch_cmd
    self._connect()
  File "C:\Users\Orange\AppData\Local\Programs\Python\Python37\lib\site-packages\pymemcache\client\base.py", line 336, in _connect
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。


----#2020.10.15_17:38:57.614|[ERROR-BREAK]:func_name=handle_msg
Traceback (most recent call last):
  File "E:\google下载\igotolibrary-master\utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "E:\google下载\igotolibrary-master\mhandle_content.py", line 743, in handle_msg
    reply_text = CmdFunction.FUNCTION_MAP[cmd_kind](userid, content)
  File "E:\google下载\igotolibrary-master\mhandle_content.py", line 554, in query_result
    reply_str = CmdFunction.parse_dct_from_mc(result)
  File "E:\google下载\igotolibrary-master\mhandle_content.py", line 522, in parse_dct_from_mc
    reply_str += CF.TRACE_FORMAT['head'].format(status=flag[status] + status, school_name=result_dct.get('school_name', default_value),
AttributeError: 'str' object has no attribute 'get'

**Comment by Zi-x** [comment]
![20201015183444](https://user-images.githubusercontent.com/47513451/96112411-26865600-0f15-11eb-94eb-0fd25209645a.png)
这是任务提交成功的截图，问题应该是出在网页执行部分，按着错误代码查了很久，想着能不能自己解决，然而今天图书馆都没去，在寝室弄了一天了还是不行，如果大佬看到的话，希望能指点一下，毕竟您是作者，可能几句话就胜过我一天的琢磨(瞎改)，我已经弄的魔怔了😭）。

**Comment by aohuidai** [comment]
加油，来着菜鸡的安慰

**Comment by aohuidai** [comment]
加油，…来自菜鸡的安慰（这也是我的心病）

**Comment by qmppz** [comment]
加油🤔

**Comment by Zi-x** [comment]
> 加油🤔

作者帮帮俺，抓住(｡･ω･｡)问几个问题，请问(网络上)要设置(开放)端口什么的吗？；然后就是我指令前面加了test后，没有回复我内测，是不是没进入内测版本呢？(但程序收到了我的扩展指令呀)；还有抢座任务布置成功后一直没有任何反馈错误信息？(成功,失败,出错..)；我看源码按理来说应该会有错误log，这点很奇怪，感觉就差某个小地方就能成功一样；还有那个IPProxyPool这个文件夹对程序来说重要吗？(如果是网络问题的话)。由于自己不是计算机专业的，实在是找不出到底问题是出在哪一个地方，网络，代码，或是其它地方。。。。可以的话回答俺一下吧(可能有的问题很弱智)；这个程序部署到自己PC(or服务器)上应该注意哪些地方的改动呢。Σ_(꒪ཀ꒪」∠)_作者大大所有的文章俺都看了一遍，实在无能为力了。。。希望作者大大不要嫌弃我Σ(ﾟдﾟ;)

**Comment by Zi-x** [comment]
> 加油，…来自菜鸡的安慰（这也是我的心病）

我真的是一根筋，现在满脑子只希望能搞定这个，考研学习要是这么一根筋就好了.......

**Comment by Zi-x** [comment]
下面是今天执行任务后数据库的信息，task_result这一项没有东西，如果有些错误提示的话，我还能继续往下琢磨琢磨，现在不知道从哪排查起了o(╥﹏╥)o
![1](https://user-images.githubusercontent.com/47513451/96119150-1ffcdc00-0f1f-11eb-802f-583e5fda6d6e.png)
![2](https://user-images.githubusercontent.com/47513451/96119153-21c69f80-0f1f-11eb-9d6a-239a8215d5e2.png)
![3](https://user-images.githubusercontent.com/47513451/96119155-225f3600-0f1f-11eb-9e28-c5d7f5d3182c.png)
![4](https://user-images.githubusercontent.com/47513451/96119157-22f7cc80-0f1f-11eb-8b42-e9bb13996740.png)
![5](https://user-images.githubusercontent.com/47513451/96119161-23906300-0f1f-11eb-9e78-710a869d7145.png)

**Comment by Zi-x** [comment]
> 加油🤔

作者大大，能不能把你的服务器借我看看(仅看看，别的我也不会)
我就用FTP看看抢座脚本在服务器上的文件结构和内容(｀・ω・´)，(我自己真的不知道怎么改了)

**Comment by Zi-x** [comment]
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
这是因为没有得到抢座网页的同意吗，阻止进入它的抢座网页？

**Comment by just-test-2021** [comment]
老哥现在还在弄吗 方便交流一下嘛
