### ISSUE TITLE
成功了一次定时抢座

### ISSUE THREAD

**Issue by Zi-x** [qmppz/igotolibrary#27]
成功了一次定时抢座，原来之前是mainloop没运行，但是现在还是有问题如果task里有捡漏的任务（就算是以前布置的）
也会导致error，而且不管是抢座成功或失败一直都有这个错
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/utils.py", line 1072, in get_value
    result = self.client.get(key=key, default=default)
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 534, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 899, in _fetch_cmd
    self._connect()
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 336, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused

所以现在感觉功能很不稳定的样子o(╥﹏╥)o😭
如下是mainloop的日志：

SELECT * FROM  today_task WHERE (task_kind='realtime'  AND open_time < '19:39:30') OR ( open_time >= '19:36:30' AND open_time < '19:39:30' ) ;  [{'id': 4, 'task_id': 22226, 'userid': 'zi', 'task_kind': 'realtime', 'wechat_sess_id': 'wechatSESS_ID=46c21bcccca7f1d157d5bb20df73f66d9c334ab96e84053b', 'succ_failed': '', 'detail_info': '', 'others_result_info': '', 'user_name': '子', 'school_name': '江汉大学', 'schl_abbr': 'jhun', 'open_time': '14:40:51', 'classroom_name1': '二楼报刊阅览室 (2楼)', 'libid1': 20027, 'seat_num1': 0, 'coordinate1': '0', 'classroom_name2': '二楼报刊阅览室 (2楼)', 'libid2': 20027, 'seat_num2': 0, 'coordinate2': '0', 'serverid': 'b9fc7bd86d2eed91b23d7347e0ee995e|1602830449|1570361133', 'comment_info': '', 'submit_time': '2020-10-16 14:40:51', 'pattern': 'TODAY', 'platform': 'IGTL', 'others_info': '{"all_lib_clssrm": {"20027": "\\u4e8c\\u697c\\u62a5\\u520a\\u9605\\u89c8\\u5ba4 (2\\u697c)", "10158": "\\u4e09\\u697c\\u5927\\u5385 (3\\u697c)", "115599": "304\\u4e09\\u697c\\u4eba\\u6587\\u793e\\u4f1a\\u79d1\\u5b66\\u9605\\u89c8\\u5ba4\\uff08\\u4e09 \\uff09 (3\\u697c)", "116299": "301\\u4e09\\u697c\\u4eba\\u6587\\u793e\\u4f1a\\u79d1\\u5b66\\u9605\\u89c8\\u5ba4\\uff08\\u4e00\\uff09 (3\\u697c)", "10156": "\\u56db\\u697c\\u5927\\u5385 (4\\u697c)", "115578": "401\\u5916\\u6587\\u6587\\u732e\\u9605\\u89c8\\u5ba4 (4)", "117895": "405\\u5916\\u6587\\u8fc7\\u520a\\u9605\\u89c8\\u5ba4 (4\\u697c)", "10154": "503\\u4eba\\u6587\\u793e\\u4f1a\\u79d1\\u5b66\\u6587\\u732e\\u5178\\u85cf\\u9605\\u89c8\\u5ba4\\uff08\\u4e8c\\uff09 (5\\u697c)", "20030": "505\\u81ea\\u79d1\\u5178\\u85cf (5\\u697c)", "115564": "501\\u793e\\u79d1\\u6587\\u732e\\u5178\\u85cf\\u9605\\u89c8\\u5ba4 (5)", "115571": "\\u4e94\\u697c\\u5927\\u5385 (5)"}}'}]
----#2020.10.16_19:36:31.086|[run] realtime_1_22226_22226 thread start run
----#2020.10.16_19:36:31.087|[ERROR-BREAK]:func_name=get_value
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/utils.py", line 1072, in get_value
    result = self.client.get(key=key, default=default)
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 534, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 899, in _fetch_cmd
    self._connect()
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 336, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused

----#2020.10.16_19:36:31.087|[ERROR-BREAK]:func_name=run
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/reserve.py", line 551, in run
    if task['task_id'] == tmp_mc_trace['task_id']:
TypeError: string indices must be integers

**Comment by aohuidai** [comment]
芜湖，太强了

**Comment by Zi-x** [comment]
> 芜湖，太强了
仅仅一次在本地上定时抢座成功了，但是接下来在服务器上却还没成功
问题很多：当候选座位1占用时，座位2(设置的随机）就完全没用了，首先在座位1失败后，过了十几秒才开始座位2的抢座，虽然程序发现了还有三个空位，但是却error了？？？导致直接失败抢座。。

现在看来必须得只考虑定时抢座功能且只能靠，座位1(而且必须设定确切的位置，0也不行很不稳定，暂时没成功)。而且捡漏功能根本不行，不仅会被程序不断拿出运行，进而干扰其他任务，导致其他任务都失败，就算只布置捡漏功能，也不能捡漏成功
暂时就是这样
同时这个错误  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 336, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
也是自始至终一直阴魂不散，问题还有很多

下面是mainloop.log


--#2020.10.16_20:12:31.103|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 20.0 s, threadID= 1
----#2020.10.16_20:12:51.109|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 20.0 s, threadID= 1
----#2020.10.16_20:13:11.129|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 20.0 s, threadID= 1
----#2020.10.16_20:13:31.146|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 5.0 s, threadID= 1
----#2020.10.16_20:13:36.151|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 5.0 s, threadID= 1
----#2020.10.16_20:13:41.154|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 5.0 s, threadID= 1
----#2020.10.16_20:13:46.156|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 5.0 s, threadID= 1
----#2020.10.16_20:13:51.161|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 5.0 s, threadID= 1
----#2020.10.16_20:13:56.167|[run] realtime_1_22226_22226 task-start=20:14:00 delay= 3.833 s, threadID= 1
----#2020.10.16_20:14:00.003|[run] realtime_1_22226_22226 try 候选一:[二楼报刊阅览室 (2楼)]的[160]号座位:
----#2020.10.16_20:14:00.003|[r_s] thread=realtime_1_22226_22226|   lib_seat_info= 候选一:[二楼报刊阅览室 (2楼)]的[160]号座位: libid 20027 coordinate 9,28
----#2020.10.16_20:14:00.003|[r_s] thread=realtime_1_22226_22226|   ||candidate libid= [('20027', '二楼报刊阅览室 (2楼)')]
----#2020.10.16_20:14:03.179|[r_s] thread=realtime_1_22226_22226|   ||candidate seat= [('160', '9,28')]
----#2020.10.16_20:14:03.332|[r_s] thread=realtime_1_22226_22226|   REG_HEXCODE_URL= https://static\.wechat\.v2\.traceint\.com/template/theme2/cache/layout/.+?
----#2020.10.16_20:14:03.343|[r_s] thread=realtime_1_22226_22226|   hexch_js_url= https://static.wechat.v2.traceint.com/template/theme2/cache/layout/6jWRNNwenNyhpBMK.js ts= 3.3396907806396485
----#2020.10.16_20:14:03.459|[r_s] thread=realtime_1_22226_22226|   ajax_url= "https://wechat.v2.traceint.com/index.php/reserve/get/"+"libid="+h+"&"+e.dec("7ahufnUCbNod8F6rJRPvgD")+"="+s+"&yzm="+t ts= 3.455573892593384
----#2020.10.16_20:14:06.464|[ERROR-BREAK]:func_name=reserve_a_seat
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/reserve.py", line 393, in reserve_a_seat
    tmp = execjs.compile(hexch_js_code)
  File "/usr/local/lib/python3.6/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/usr/local/lib/python3.6/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/usr/local/lib/python3.6/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.


----#2020.10.16_20:14:11.469|[run] realtime_1_22226_22226 try 候选二:[二楼报刊阅览室 (2楼)]的[0]号座位:
----#2020.10.16_20:14:11.469|[r_s] thread=realtime_1_22226_22226|   lib_seat_info= 候选二:[二楼报刊阅览室 (2楼)]的[0]号座位: libid 20027 coordinate 0
----#2020.10.16_20:14:11.469|[r_s] thread=realtime_1_22226_22226|   ||candidate libid= [('20027', '二楼报刊阅览室 (2楼)')]
----#2020.10.16_20:14:14.747|[r_s] thread=realtime_1_22226_22226|   ||candidate seat= [('75', '20,12'), ('304', '20,99'), ('184', '9,16')]
----#2020.10.16_20:14:14.907|[r_s] thread=realtime_1_22226_22226|   REG_HEXCODE_URL= https://static\.wechat\.v2\.traceint\.com/template/theme2/cache/layout/.+?
----#2020.10.16_20:14:14.918|[r_s] thread=realtime_1_22226_22226|   hexch_js_url= https://static.wechat.v2.traceint.com/template/theme2/cache/layout/E6kb6MKjydDA3biK.js ts= 3.448747968673706
----#2020.10.16_20:14:15.059|[r_s] thread=realtime_1_22226_22226|   ajax_url= "https://wechat.v2.traceint.com/index.php/reserve/get/"+"libid="+h+"&"+e.dec("im6G0wSB6QY1w0BS")+"="+s+"&yzm="+t ts= 3.589938735961914
----#2020.10.16_20:14:18.062|[ERROR-BREAK]:func_name=reserve_a_seat
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/reserve.py", line 393, in reserve_a_seat
    tmp = execjs.compile(hexch_js_code)
  File "/usr/local/lib/python3.6/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/usr/local/lib/python3.6/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/usr/local/lib/python3.6/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.


----#2020.10.16_20:14:18.062|[run] realtime_1_22226_22226 delaytime= 20
----#2020.10.16_20:14:38.074|[task_ending] trace_dct_ls= [{'exe_time': '2020.10.16_20:14:00.103', 'libid': '20027', 'clssrm': '二楼报刊阅览室 (2楼)', 'seat_num': '160', 'cordinate': '9,28', 'code': -1, 'msg': '致命错误, 服务器无响应导致退出', 'completed_flag': 'continue'}, {'exe_time': '2020.10.16_20:14:11.569', 'libid': '20027', 'clssrm': '二楼报刊阅览室 (2楼)', 'seat_num': '75', 'cordinate': '20,12', 'code': -1, 'msg': '致命错误, 服务器无响应导致退出', 'completed_flag': 'continue'}]  
task= {'id': 2, 'task_id': 22226, 'userid'
----#2020.10.16_20:14:38.079|[task_ending] refersh memchcae, key= reserve_zi
----#2020.10.16_20:14:38.080|[ERROR-BREAK]:func_name=set_value
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/utils.py", line 1063, in set_value
    self.client.set(key=key, value=value, expire=expire_second)
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 379, in set
    flags=flags)[key]
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 968, in _store_cmd
    self._connect()
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 336, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
----#2020.10.16_20:14:38.080|[run] realtime_1_22226_22226 Done

**Comment by aohuidai** [comment]
主要是作者写的时候写的服务器的脚本，自己用的话这个项目实在是有点大，

**Comment by aohuidai** [comment]
想把主逻辑拿出来保留基本的功能就好，就是那个用execjs执行js代码有点问题，实在是整不明白

**Comment by Zi-x** [comment]
> 想把主逻辑拿出来保留基本的功能就好，就是那个用execjs执行js代码有点问题，实在是整不明白

是的，现在服务器定时抢座执行不了
比较本地运行的log，execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.是这里出现问题，但是我本地运行没出现这个问题，很奇怪

**Comment by Zi-x** [comment]
> 想把主逻辑拿出来保留基本的功能就好，就是那个用execjs执行js代码有点问题，实在是整不明白

你知道sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused这个error是什么原因吗

**Comment by aohuidai** [comment]
服务器端口没开？

**Comment by Zi-x** [comment]
> 服务器端口没开？

我本地就算抢座成功了也是这个错误，百度开端口都试过，不知道是那个端口
