### ISSUE TITLE
部署在白嫖的aliyun服务器成功了2次定时抢座，但是速度不忍直视

### ISSUE THREAD

**Issue by Zi-x** [qmppz/igotolibrary#28]
之前的服务器上失败是因为node.js没有安装，安装后成功了两次，但是这速度实在是不忍直视，29秒才预定成功
---#2020.10.16_21:59:09.551|[run] realtime_1_22226_22226 delaytime= 20
----#2020.10.16_21:59:29.571|[task_ending] trace_dct_ls= [{'exe_time': '2020.10.16_21:59:00.103', 'libid': '10156', 'clssrm': '四楼大厅 (4楼)', 'seat_num': '210', 'cordinate': '13,8', 'code': 0, 'msg': '预定成功', 'completed_flag': 'completed'}]  
啊这，每天早上位置可是1秒就无了，实在是不知道原因(为什么这么慢)，希望作者大大看到能回复一下我😭，中间还delaytime了20秒，就算不delay，9秒也太慢了。同时pymemcache的错误依然英魂不散。求解决！！！！！

以下是log：

wechatSESS_ID=3e4f1dddb623cbc13f747e1931a31aa1b261122a6b863b58', 'succ_failed': '', 'detail_info': '', 'others_result_info': '', 'user_name': '子', 'school_name': '江汉大学', 'schl_abbr': 'jhun', 'open_time': '21:59:00', 'classroom_name1': '四楼大厅 (4楼)', 'libid1': 10156, 'seat_num1': 210, 'coordinate1': '13,8', 'classroom_name2': '四楼大厅 (4楼)', 'libid2': 10156, 'seat_num2': 0, 'coordinate2': '0', 'serverid': 'd3936289adfff6c3874a2579058ac651|1602856638|1570361133', 'comment_info': '', 'submit_time': '2020-10-16 21:57:19', 'pattern': 'TODAY', 'platform': 'IGTL', 'others_info': '{"all_lib_clssrm": {"20027": "\\u4e8c\\u697c\\u62a5\\u520a\\u9605\\u89c8\\u5ba4 (2\\u697c)", "10158": "\\u4e09\\u697c\\u5927\\u5385 (3\\u697c)", "10156": "\\u56db\\u697c\\u5927\\u5385 (4\\u697c)", "115571": "\\u4e94\\u697c\\u5927\\u5385 (5)"}}', 'open_time_ts': 1602856740, 'task_result': 'school:江汉大学-jhun\ntask_id:22226\n任务提交:2020-10-16 21:57:19\n\n'}
----#2020.10.16_21:57:31.096|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 20.0 s, threadID= 2
----#2020.10.16_21:57:51.107|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 20.0 s, threadID= 2
----#2020.10.16_21:58:11.115|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 20.0 s, threadID= 2
----#2020.10.16_21:58:31.118|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 5.0 s, threadID= 2
----#2020.10.16_21:58:36.123|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 5.0 s, threadID= 2
----#2020.10.16_21:58:41.126|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 5.0 s, threadID= 2
----#2020.10.16_21:58:46.132|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 5.0 s, threadID= 2
----#2020.10.16_21:58:51.137|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 5.0 s, threadID= 2
----#2020.10.16_21:58:56.137|[run] realtime_1_22226_22226 task-start=21:59:00 delay= 3.863 s, threadID= 2
----#2020.10.16_21:59:00.003|[run] realtime_1_22226_22226 try 候选一:[四楼大厅 (4楼)]的[210]号座位:
----#2020.10.16_21:59:00.003|[r_s] thread=realtime_1_22226_22226|   lib_seat_info= 候选一:[四楼大厅 (4楼)]的[210]号座位: libid 10156 coordinate 13,8
----#2020.10.16_21:59:00.003|[r_s] thread=realtime_1_22226_22226|   ||candidate libid= [('10156', '四楼大厅 (4楼)')]
----#2020.10.16_21:59:03.188|[r_s] thread=realtime_1_22226_22226|   ||candidate seat= [('210', '13,8')]
----#2020.10.16_21:59:03.243|[r_s] thread=realtime_1_22226_22226|   REG_HEXCODE_URL= https://static\.wechat\.v2\.traceint\.com/template/theme2/cache/layout/.+?
----#2020.10.16_21:59:03.247|[r_s] thread=realtime_1_22226_22226|   hexch_js_url= https://static.wechat.v2.traceint.com/template/theme2/cache/layout/2cG4ASKi8GMEbees.js ts= 3.2438379287719727
----#2020.10.16_21:59:03.360|[r_s] thread=realtime_1_22226_22226|   ajax_url= "https://wechat.v2.traceint.com/index.php/reserve/get/"+"libid="+e+"&"+s.dec("UACzzAeCGn61")+"="+h+"&yzm="+t ts= 3.3567777633666993
----#2020.10.16_21:59:06.411|[r_s] thread=realtime_1_22226_22226|   http_hexch_seatinfo= https://wechat.v2.traceint.com/index.php/reserve/get/libid=10156&EhyWdt=13,8&yzm= ts= 6.408551549911499
----#2020.10.16_21:59:09.415|[r_s] thread=realtime_1_22226_22226|   request, tmp_trace_dct= {'exe_time': '2020.10.16_21:59:00.103', 'libid': '10156', 'clssrm': '四楼大厅 (4楼)', 'seat_num': '210', 'cordinate': '13,8', 'code': '', 'msg': '没有合适的'}
----#2020.10.16_21:59:09.551|[r_s] thread=realtime_1_22226_22226|   reserve response= {"code":0,"msg":"\u9884\u5b9a\u6210\u529f","token":"23876133-5f2670f17719dcd34cce103d6e7cf73a","url":"https:\/\/wechat.v2.traceint.com\/index.php\/success\/23876133-5f2670f17719dcd34cce103d6e7cf73a.html"}
----#2020.10.16_21:59:09.551|[run] realtime_1_22226_22226 delaytime= 20
----#2020.10.16_21:59:29.571|[task_ending] trace_dct_ls= [{'exe_time': '2020.10.16_21:59:00.103', 'libid': '10156', 'clssrm': '四楼大厅 (4楼)', 'seat_num': '210', 'cordinate': '13,8', 'code': 0, 'msg': '预定成功', 'completed_flag': 'completed'}]  
task= {'id': 6, 'task_id': 22226, 'userid'
----#2020.10.16_21:59:29.577|[task_ending] refersh memchcae, key= reserve_zi
----#2020.10.16_21:59:29.578|[ERROR-BREAK]:func_name=set_value
Traceback (most recent call last):
  File "/root/igotolibrary/utils.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/root/igotolibrary/utils.py", line 1063, in set_value
    self.client.set(key=key, value=value, expire=expire_second)
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 379, in set
    flags=flags)[key]
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 968, in _store_cmd
    self._connect()
  File "/usr/local/lib/python3.6/site-packages/pymemcache/client/base.py", line 336, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by Zi-x** [comment]
是不是reserve.py里有很多time.sleep(3)(3秒好几个还有8-20秒随机暂停的)，有的时长和.log里的时间差很吻合，不知道能不能把这些暂停都删掉(ˇˍˇ)

**Comment by Zi-x** [comment]
> 是不是reserve.py里有很多time.sleep(3)(3秒好几个还有8-20秒随机暂停的)，有的时长和.log里的时间差很吻合，不知道能不能把这些暂停都删掉(ˇˍˇ)
删掉sleep后，现在基本解决了速度在0.7左右，虽然有些地方还是有些疑问。但是，作者已经把评论关了，想必是不想提这个了吧，我也不提了，就这样吧，债见

**Comment by wangjunhao999** [comment]
@Zi-x  最近我也在研究这个，一起来探讨下这个，有意向的话邮箱联系我1138700280@qq.com，如果单纯只要抢座的话，就只保留那几个函数就行了，然后服务器设置定时执行就好了
