### ISSUE TITLE
公众号不能用了，大佬

### ISSUE THREAD

**Issue by liubo001** [qmppz/igotolibrary#6]
公众号出问题了

**Comment by qmppz** [comment]
稍等...

**Comment by liubo001** [comment]
谢谢
---原始邮件---
发件人:"han"<notifications@github.com>
发送时间:2019年12月1日 星期日 下午8:22
收件人:"qmppz/igotolibrary"<igotolibrary@noreply.github.com>
抄送:"index"<502609545@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [qmppz/igotolibrary] 公众号不能用了，大佬 (#6)

稍等...

&mdash;

**Comment by liubo001** [comment]
公众号又不能用了

**Comment by qmppz** [comment]
理论能用, 若还出现问题请联系公众号管理员
